[build]
  publish = "dist"
  command = "npm ci --include=dev && npm run build"

[build.environment]
  NODE_VERSION = "20"
  NPM_CONFIG_PRODUCTION = "false"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

# Configuração do secrets scanning
[secrets]
  # Ignorar arquivos de build que podem conter variáveis de ambiente do frontend
  SECRETS_SCAN_OMIT_PATHS = ["dist/**", "*.js.map", "*.css.map"]
  # Permitir essas chaves específicas do EmailJS no frontend
  SECRETS_SCAN_OMIT_KEYS = ["VITE_EMAILJS_PUBLIC_KEY", "VITE_EMAILJS_SERVICE_ID", "VITE_EMAILJS_TEMPLATE_ID"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
